name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compile test
        run: |
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 20
          sudo apt install ninja-build
          tool/compile.sh
