name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compile test
        run: |
          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 20
          ./build.sh src/tool/test_compile.cpp
